Using pad_to_size function to remove duplicate code in pad_arrays
awslabs/gluon-ts pull request #1047
Opened 2020-09-21 16:32 UTC by dcmaddix

*Description of changes:*
- Moved `pad_arrays` to `util.py`
- Used `pad_to_size` function to remove duplicate code and return before calling `nd.pad` if no padding is needed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-22 14:25 UTC, lostella requested changes
@dcmaddix it would be nice to keep the code that requires MXNet under the `gluonts.mx` subpackage, so that it's clear which imports path require MXNet being installed and which ones don't.

I guess `pad_arrays` could be part of `gluonts.mx.utils`?

2020-09-22 23:07 UTC, dcmaddix commented
> @dcmaddix it would be nice to keep the code that requires MXNet under the `gluonts.mx` subpackage, so that it's clear which imports path require MXNet being installed and which ones don't.
> 
> I guess `pad_arrays` could be part of `gluonts.mx.utils`?

yes, I moved it back to `mx.batchify`.  Thanks!

2020-09-28 18:57 UTC, lostella submitted a review, later dismissed
Looks good to me! I guess the number of test cases changed because of this PR, and this makes some other flaky tests fail consistently -- we should robustify those

2020-09-29 18:59 UTC, lostella approved these changes

2020-09-29 19:00 UTC, merged