Fixes awslabs/gluon-ts#1106
awslabs/gluon-ts pull request #1125
Opened 2020-10-31 16:08 UTC by kaijennissen

#1106

Added custom_eval_fn argument to Evaluator/MultivariateEvaluator class

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-31 17:19 UTC, kaijennissen commented
@lostella `pytest test/model/tft/test_model.py` sometimes fails due to a timeout error even on `master`. Is there a way I can fix this?

2020-11-01 07:13 UTC, lostella commented
I think you can mark it as skipped, and we can figure it out separately. To do that, add the following decorator to the test that times out:

```python 
@pytest.mark.skip("This times out frequently.")
```

2020-11-02 13:26 UTC, lostella commented on src/gluonts/evaluation/_base.py
> +    Option to include custom evaluation metrics. Expected input is
```suggestion
    custom_eval_fn
        Option to include custom evaluation metrics. Expected input is
```

2020-11-02 13:38 UTC, lostella requested changes
Hey @kaijennissen thanks for this! Looks good overall, I just have some comments inline

2020-11-02 13:38 UTC, lostella commented on src/gluonts/evaluation/_base.py
> +                            ),
Since it's just two values, maybe it is better to use an `if` here. We can then rework this whenever needed

2020-11-02 13:38 UTC, lostella commented on src/gluonts/evaluation/_base.py
> +                    custom_agg = {k: agg_type}
I'm not sure I understand the need for the `try` block here, what could go wrong?

2020-11-02 20:46 UTC, lostella approved these changes

2020-11-02 21:13 UTC, merged