Did things
awslabs/gluon-ts pull request #1544
Opened 2021-06-07 19:15 UTC by zoolhasson

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

2021-06-08 08:25 UTC, lostella commented
marked this as breaking to prevent it from ending up in a previous release branch

2021-06-09 16:50 UTC, dcmaddix requested changes
sounds good to me - just minor changes we can merge after checking with @lostella on the breaking change.

2021-06-09 16:50 UTC, dcmaddix commented on src/gluonts/model/rotbaum/_model.py
> +        if model_is_already_trained is False:
can simplify to:
`if not model_is_already_trained:`

2021-06-09 16:50 UTC, dcmaddix commented on src/gluonts/model/rotbaum/_model.py
> +        final_id = df["bins"].drop_duplicates().values[-1]
`bins = df["bins"].drop_duplicates().values()`, so you only have to compute once and then take the last and second to last element

2021-06-09 16:50 UTC, dcmaddix commented on src/gluonts/model/rotbaum/_model.py
> +            self.id_to_bins[final_id] = (
`self.id_to_bins[final_id] += self.id_to_bins[penultimate_id]`

2021-06-09 20:26 UTC, dcmaddix approved these changes

2021-06-09 20:26 UTC, merged