torch predictor use inference_mode decorator
awslabs/gluon-ts pull request #1765
Opened 2021-11-11 08:43 UTC by kashif

*Issue #, if available:*

*Description of changes:*

inference mode also disables version counting and metadata tracking

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

2021-11-16 20:25 UTC, lostella requested changes
Looks good, I have left some comments inline.

It looks like this PR is really about bumping the versions of the adopted frameworks, so maybe the PR title should reflect that?

2021-11-16 20:25 UTC, lostella commented on src/gluonts/torch/model/estimator.py
> +            train_dataloaders=training_data_loader,
This used to be different in PL 1.3.1, see https://pytorch-lightning.readthedocs.io/en/1.3.1/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer.fit

So apparently PL 1.4.0 introduced a breaking change, see https://pytorch-lightning.readthedocs.io/en/1.4.0/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer.fit

We should probably update the requirement on PL here, too? https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements-pytorch.txt

2021-11-16 20:25 UTC, lostella commented on src/gluonts/torch/model/predictor.py
> +        with torch.inference_mode():
Looks like this was introduced in torch==1.9.0, at least from the documentation, so this probably requires bumping the requirement? https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements-pytorch.txt

2021-11-16 20:25 UTC, lostella commented on .github/workflows/tests.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9]
Maybe we can enable testing on 3.9 as part of a separate PR @jaheba ?

2021-11-17 09:00 UTC, kashif commented
thanks @lostella I'll get it fixed!

2021-11-17 10:03 UTC, lostella commented on .github/workflows/tests.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9]
Also installing autogluon on python 3.9 appears to be giving issues in the test workflow @kashif so one more reason to split this up :-)

2021-11-21 13:04 UTC, kashif commented
@lostella will be ready for another review. Thanks!

2021-11-22 14:10 UTC, kashif commented
@jaheba can you kindly merge this before your fixes #1786? Else I might get some conflicts... thanks!

2021-11-22 14:23 UTC, jaheba commented
> @jaheba can you kindly merge this before your fixes #1786? Else I might get some conflicts... thanks!

Can do that.

2021-11-22 14:26 UTC, jaheba commented on .github/workflows/docs.yml
> +        python -m pip install pip
@kashif Can you revert these changes so we don't get a conflict in #1786?

Thanks!

2021-11-22 14:53 UTC, lostella submitted a review, later dismissed
What @jaheba said, otherwise looks good to me, thank you @kashif!

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/docs.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/flake8.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/mxnet_nightly.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/style_type_checks.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/test_release_unix_nightly.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/test_release_win32_nightly.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:53 UTC, jaheba commented on .github/workflows/tests.yml
> +        python -m pip install pip
```suggestion
        python -m pip install pip==20.2
```

2021-11-22 14:54 UTC, lostella approved these changes

2021-11-22 14:57 UTC, kashif commented
@lostella @jaheba sorry missed it... was in a call thanks for doing this!

2021-11-22 15:00 UTC, merged