Fix mean in AffineTransformedDistribution
awslabs/gluon-ts pull request #2015
Opened 2022-06-10 16:10 UTC by stailx

Incorrect mean property in AffineTransformedDistribution.
Scaling was not taken into account in an Affine Transform.
Mathematic proof: mean(y)= mean(scale * x+loc ) = scale * mean(x) + loc.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-10 17:35 UTC, lostella requested changes
@stailx thanks for spotting this! I only have one comment to be addressed

2022-06-10 17:35 UTC, lostella commented on src/gluonts/mx/distribution/transformed_distribution.py
> +            self.base_distribution.mean * self.scale
This does not account for the case `self.scale = None`. You could use `scale` defined as

```python
scale = self.scale if self.scale is not None else 1
```

2022-06-13 11:48 UTC, lostella approved these changes
@stailx thanks again for spotting this! I took the liberty of pushing this over the finish line, I hope you don't mind

🚀

2022-06-13 12:08 UTC, merged

2022-06-13 12:13 UTC, kashif commented
well spotted @stailx