Minor improvements to the hierarchical model
awslabs/gluon-ts pull request #2036
Opened 2022-06-14 17:27 UTC by rshyamsundar

*Description of changes:*
Minor enhancements: 
* better handling of user-errors
* logging of coherency error during prediction (even if the samples are not reconciled) for better reporting of results

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

2022-06-14 19:22 UTC, lostella requested changes

2022-06-14 19:22 UTC, lostella commented on src/gluonts/model/deepvar_hierarchical/_estimator.py
> +            logger = logging.getLogger("gluonts").getChild("model")
Elsewhere we follow the convention of creating a logger at the module level, named after the module, see eg https://github.com/awslabs/gluon-ts/blob/e7e06dd97029efe5f0368a39604e2572f98008a2/src/gluonts/shell/train.py#L32

2022-06-14 19:22 UTC, lostella commented on src/gluonts/model/deepvar_hierarchical/_network.py
> +            self.logger = logging.getLogger("gluonts").getChild("model")
Same as above

2022-06-14 19:22 UTC, lostella commented on src/gluonts/model/deepvar_hierarchical/_network.py
> +            self.logger.info(
Same as above

2022-06-14 19:22 UTC, lostella commented on test/model/deepvar_hierarchical/test_coherency_error.py
> +    coherency_error,
Just out of curiosity: is “coherency” just a better term for the concept?

2022-06-14 19:25 UTC, lostella commented on test/model/deepvar_hierarchical/test_coherency_error.py
> +    coherency_error,
Isn’t it “coherence” also?

2022-06-15 09:20 UTC, rshyamsundar commented on test/model/deepvar_hierarchical/test_coherency_error.py
> +    coherency_error,
I also prefer coherence but @lucienwerner insisted coherency is more appropriate and we used/defined that term "coherency error" in the paper.

2022-06-15 09:28 UTC, lostella approved these changes
Thanks @rshyamsundar! Looks good to me

2022-06-15 09:58 UTC, merged