Add tutorial with data splitting examples
awslabs/gluon-ts pull request #2157
Opened 2022-07-13 11:10 UTC by npnv

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

2022-07-13 13:17 UTC, jaheba reviewed
It looks like there is a space ` ` in the file name.

2022-07-13 13:17 UTC, jaheba commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +    end = entry['start'] + len(entry['target']) * entry['start'].freq
If `start` is a period, you can just do 
```suggestion
    end = entry['start'] + len(entry['target'])
```

2022-07-14 08:53 UTC, jaheba requested changes, later dismissed
Can you remove the space from `docs/tutorials/data_manipulation/data _splitter_example.md`? Thanks!

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +# Data Splitter Usage
Maybe a better title is 
```suggestion
# Splitting datasets into training and test
```

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +```
Are all of these needed?

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +```
I believe also many of these are not needed

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +        plt.legend(["sub dataset"], loc="upper left")
Can we add the highlighted regions to the legend? So it's clear what is train/input/label

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +```
No need to have subsections. Also, try to just do as little code as possible for this part:
- load data from csv into dataframe
- resample to 1h
- plot

One or two cells are sufficient for this

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +we will take training data up to date `2015-04-07 00:00:00`, then generate several test instances from there onwards
```suggestion
We will take training data up to date `2015-04-07 00:00:00`, then generate several test instances from there onwards.
```

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +    plt.figure(figsize=(20,3))
You can set this once and for all on top of the notebook with
```python
plt.rcParams["figure.figsize"] = (20, 3)
```

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +    return start, end
This could contain more of the logic, to simplify the following cells. For example

```python
def highlight_entry(entry, color):
    start = entry['start']
    end = entry['start'] + len(entry['target'])
    plt.axvspan(start, end, facecolor=color, alpha=.2)
```

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +        plt.grid(which="both")
maybe we can also set the grid once and for all

2022-07-14 09:10 UTC, lostella commented on docs/tutorials/data_manipulation/data _splitter_example.md
> +_, test_template = split(sub_dataset, date=TEST_START_DATE)
No need to declare these as variables, just assign them in `date=` directly

2022-07-14 09:12 UTC, lostella commented
@npnv can you also rename the file to have `.md.template` suffix?

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +As a result, the `split` method returns the splited dataset, consisting of the training data `training_dataset` and the TestTemplate objectives `test_template` which knows how to generate test data `
```suggestion
In this notebook, we are going to show how to split the entries of a dataset, along time, to construct training and test subsets of data (or training/validation/test). Specifically, we'll use the `split` function. This needs to be given:
- the `dataset` that we want to split;
- an `offset` or a `date`, but not both simultaneously. These two arguments are provided for the function to know how to slice training and test data, based on a fixed integer offset or a ``pandas.Period``, respectively.

As a result, the `split` method returns the splited dataset, consisting of the training data `training_dataset` and the TestTemplate objectives `test_template` which knows how to generate test data `test_pairs` using the memeber function `generate_instances`.
```

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +from gluonts.dataset.field_names import FieldName
```suggestion
```

I would avoid importing this, and directly use `"start"` and `"target"`

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +```python
No need to explain this, since the user is not interested, just set the options in the same cells as the import

```suggestion

```

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +```
No need to plot both, just the data we'll use

```suggestion
This is what the data looks like:

```python
df_resample.plot()
```

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +- In the `plot_dataset_splitting` method, we plot the `original_dataset` and highlight the corresponding splitted `training_dataset` and `test_pairs`.
Again, there's no need to go into detail here: these are support functions used to show the splits, but the reader is really only interested in how to use `split`

```suggestion
Let's define a few helper functions to visualize data splits.
```

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +Load data from an online csv into `pandas.DataFrame`, which is a long time series, with the frequency being 5 minutes and the length being 15831, so we resample the time series into an hour bins and
```suggestion
For our examples, we will use data from the following `csv` file, which is originally sampled every 5 minutes, but we resample at hourly frequency. Note that this makes for a dataset consisting of a single time series, but everything we show here applies to any dataset, regardless of how many series it contains.
```

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +dataset = PandasDataset(df_resample.reset_index(), timestamp="timestamp", target="value")
There's a log going on here, let's simplify this a bit:
- in `read_csv` you can pass `index_col="timestamp"` and `parse_dates=True` to directly get a `DatetimeIndex`
- we can directly `.resample` and `.sum` in the same line as `.read_csv`
- we can move the creation of the `PandasDataset` to later on, after we visualized the data

As a result, this snippet should be just 2 lines of code

2022-07-14 16:28 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +
Here you can mention that we can turn the dataframe into a GluonTS dataset using `PandasDataset` and put the line that you originally had above

```python
dataset = PandasDataset(df, target="value")
```

2022-07-14 16:50 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +from gluonts.dataset.util import to_pandas
I would put the first import for `split` on top of the notebook, when we first mention `split`.
The import for `to_pandas` can go below when it's used, that is when you introduce the plotting helpers.

2022-07-18 13:47 UTC, lostella commented on docs/tutorials/data_manipulation/dataset_splitting_example.md.template
> +PUT IMPORT LINE FOR `split` HERE
@npnv don't forget to put the actual import line here

```
from gluonts.dataset.split.splitter import split
```

2022-08-03 10:54 UTC, lostella commented on src/gluonts/dataset/split/splitter.py
> +from dis import dis
Not required?

2022-08-03 11:10 UTC, lostella commented on src/gluonts/dataset/split/splitter.py
> +from dis import dis
```suggestion
```

2022-08-03 11:11 UTC, lostella commented on test/dataset/split/test_split.py
> +            )
No need to modify this to add `iter`: you can `list` both an iterable, an iterator, or a generator

2022-08-03 11:48 UTC, lostella commented on test/dataset/split/test_split.py
> +            )
```suggestion
        test_template.generate_instances(
            prediction_length=prediction_length,
            windows=windows,
            distance=distance,
            max_history=max_history,
        )
```

2022-08-03 11:49 UTC, lostella commented on test/dataset/split/test_split.py
> +        )
```suggestion
```

2022-08-03 20:03 UTC, lostella approved these changes

2022-08-03 20:06 UTC, merged