Exposing the choice of train_sampler for MQCNN and MQRNN
awslabs/gluon-ts pull request #2381
Opened 2022-10-18 14:39 UTC by sighellan

Fixes: https://github.com/awslabs/gluonts/issues/2380

*Description of changes:*
- Lets the user specify what sampler they want to use for the MQCNN and MQRNN models, keeping the default as before. 
- Adding comment to docstring describing default behaviour.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** other change

2022-10-19 09:59 UTC, lostella requested changes

2022-10-19 09:59 UTC, lostella commented on src/gluonts/mx/model/seq2seq/_mq_dnn_estimator.py
> +        Controls the sampling of windows during training.
Maybe it makes sense to similarly expose the `validation_sampler` that the upper class exposes

2022-10-20 17:01 UTC, sighellan commented on src/gluonts/mx/model/seq2seq/_mq_dnn_estimator.py
> +        Controls the sampling of windows during training.
The validation_sampler is also exposed now.

2022-10-21 10:40 UTC, sighellan commented
**Motivation for the error message update:** 

I tested the MQRNN model using `ExpectedNumInstanceSampler` for the `validation_sampler`, which resulted in failures for some but not other seeds. This could be fixed by increasing the `num_instances` parameter. 

Code: 
```
from gluonts.transform import ExpectedNumInstanceSampler
from gluonts.mx.model.seq2seq import MQRNNEstimator
from gluonts.mx import Trainer
from gluonts.dataset.repository.datasets import get_dataset
import numpy as np
import mxnet as mx

def make_shorter(tseries, ll=500):
    shorter = {
        'target': tseries['target'][-ll:],
        'start': tseries['start'] + len(tseries['target']) - ll,
        'feat_static_cat': tseries['feat_static_cat'],
        'item_id': tseries['item_id']
    }
    return shorter

dataset = get_dataset('electricity')
shorter = make_shorter(list(dataset.train)[0])
shorter_val = make_shorter(list(dataset.test)[0])

for val_num_instances in [1, 10]:
    successes = 0
    failures = 0
    print('----------------------')
    print('Validation num_instances: %s' %val_num_instances)
    for seed in [0, 1, 0, 1]:
        try:

            trainer = Trainer(epochs=1)
            np.random.seed(seed)
            mx.random.seed(seed, trainer.ctx)

            estimator_new = MQRNNEstimator(prediction_length=24, 
                                           freq='H', 
                                           trainer=trainer,
                                           train_sampler=ExpectedNumInstanceSampler(
                                           num_instances=1, min_future=24),
                                           validation_sampler=ExpectedNumInstanceSampler(
                                           num_instances=val_num_instances, 
                                               min_future=24)) 

            model_new = estimator_new.train(training_data=[shorter], 
                                            validation_data=[shorter_val])
            print('Success!')
            successes += 1
        except Exception as e:
            print(e)
            print('Failure!')
            failures += 1

    print('Successes: %s' %successes)
    print('Failures: %s' %failures)
```

Previous output: 
```
----------------------
Validation num_instances: 1

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.63it/s, epoch=1/1, avg_epoch_loss=1.85]
0it [00:00, ?it/s]

No training data batch could be constructed; this usually indicates that the training dataset is empty, or consists of too short series.
Failure!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.54it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 139.68it/s, epoch=1/1, validation_avg_epoch_loss=1.65]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.64it/s, epoch=1/1, avg_epoch_loss=1.85]
0it [00:00, ?it/s]

No training data batch could be constructed; this usually indicates that the training dataset is empty, or consists of too short series.
Failure!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.52it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 143.56it/s, epoch=1/1, validation_avg_epoch_loss=1.65]

Success!
Successes: 2
Failures: 2
----------------------
Validation num_instances: 10

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.57it/s, epoch=1/1, avg_epoch_loss=1.85]
1it [00:00, 29.02it/s, epoch=1/1, validation_avg_epoch_loss=1.67]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.57it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 30.84it/s, epoch=1/1, validation_avg_epoch_loss=1.54]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.67it/s, epoch=1/1, avg_epoch_loss=1.85]
1it [00:00, 30.93it/s, epoch=1/1, validation_avg_epoch_loss=1.67]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.60it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 29.35it/s, epoch=1/1, validation_avg_epoch_loss=1.54]

Success!
Successes: 4
Failures: 0
```

New output with more informative error message:
```
----------------------
Validation num_instances: 1

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.63it/s, epoch=1/1, avg_epoch_loss=1.85]
0it [00:00, ?it/s]

No validation data batch could be constructed; this usually indicates that the validation dataset is empty, or consists of too short series. If using a random data sampler, this might be caused by not taking enough samples.
Failure!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.65it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 123.79it/s, epoch=1/1, validation_avg_epoch_loss=1.65]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.51it/s, epoch=1/1, avg_epoch_loss=1.85]
0it [00:00, ?it/s]

No validation data batch could be constructed; this usually indicates that the validation dataset is empty, or consists of too short series. If using a random data sampler, this might be caused by not taking enough samples.
Failure!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.68it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 139.82it/s, epoch=1/1, validation_avg_epoch_loss=1.65]

Success!
Successes: 2
Failures: 2
----------------------
Validation num_instances: 10

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.59it/s, epoch=1/1, avg_epoch_loss=1.85]
1it [00:00, 30.03it/s, epoch=1/1, validation_avg_epoch_loss=1.67]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.58it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 29.19it/s, epoch=1/1, validation_avg_epoch_loss=1.54]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.60it/s, epoch=1/1, avg_epoch_loss=1.85]
1it [00:00, 30.40it/s, epoch=1/1, validation_avg_epoch_loss=1.67]

Success!

100%|████████████████████████████████████████████████████████████████| 50/50 [00:07<00:00,  6.56it/s, epoch=1/1, avg_epoch_loss=1.88]
1it [00:00, 29.65it/s, epoch=1/1, validation_avg_epoch_loss=1.54]

Success!
Successes: 4
Failures: 0
```

2022-10-24 08:09 UTC, lostella approved these changes
Thanks @sighellan! Looks good!

2022-10-24 10:09 UTC, merged