Add mint
awslabs/gluon-ts pull request #2406
Opened 2022-10-31 10:25 UTC by melopeo

*Description of changes:*

Addition of MinT reconciliation method for hierarchical time series, as done in R/hts package.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:**  new feature

2022-11-01 16:52 UTC, lostella requested changes

2022-11-01 16:52 UTC, lostella commented on src/gluonts/ext/r_forecast/_hierarchical_predictor.py
> +        nonnegative: Optional[bool] = False,
Why `Optional`? Shouldn’t this just be either `False` or `True`?

2022-11-01 16:52 UTC, lostella commented on test/conftest.py
> +    def _sine7(
I think this can be avoided? With this change you call `sine7` to construct a function, you can have `sine7` just be that function, or am I missing something?

2022-11-01 17:05 UTC, melopeo commented on test/conftest.py
> +    def _sine7(
The reason for this is that now I am adding tests for the parameter `nonnegative` to be either `True` or `False`. Previously the default value for this parameter was taken, i.e. `nonnegative = False`.

Hence, I am interested in having the `sine7` data with only positive values when `nonnegative = True`, and I thought that the proposed modification was a quick way to get this done, in particular considering that this function belongs to `conftest.py`.

Is there any suggestion or hint on how to better handle this? I will be happy to investigate it and update the code accordingly.

2022-11-02 08:21 UTC, lostella commented on test/conftest.py
> +    def _sine7(
I see, fixtures are a bit weird; nevermind! We can revisit this later if necessary

2022-11-02 08:28 UTC, melopeo commented on src/gluonts/ext/r_forecast/_hierarchical_predictor.py
> +        nonnegative: Optional[bool] = False,
Fixed!

2022-11-02 09:29 UTC, melopeo commented on test/conftest.py
> +    def _sine7(
Thanks!

2022-11-02 10:07 UTC, lostella approved these changes

2022-11-02 10:21 UTC, merged