Move from pytorch_lightning to lightning
awslabs/gluon-ts pull request #3013
Opened 2023-10-13 14:23 UTC by shchur

*Description of changes:*
- Fix the breaking change to `load_from_checkpoint` introduced by `pytorch_lightning==2.1.0`.
- Install the new package name `lightning` instead of `pytorch_lightning`
- Use the new import style `lightning.pytorch` instead of `pytorch_lightning`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

2023-10-14 10:54 UTC, lostella commented on docs/tutorials/advanced_topics/index.md
> +howto_lightning.pytorch
This slipped in I guess?

2023-10-14 10:56 UTC, lostella requested changes
One change to revert in the docs I believe, otherwise looks good, thank you @shchur!

2023-10-16 07:19 UTC, lostella commented on docs/tutorials/advanced_topics/index.md
> +howto_lightning.pytorch
```suggestion
howto_pytorch_lightning
```

2023-10-16 07:19 UTC, lostella approved these changes

2023-10-16 07:43 UTC, merged

2023-10-17 08:22 UTC, caseytomlin commented
Hi, maybe I'm doing something else wrong, but this new import syntax seems to not work with `pytorch_lightning<2.0.0`, but the [requirements](https://github.com/shchur/gluonts/blob/a8a5ec0602286f5f842bbc89adfdf838a95c2492/requirements/requirements-pytorch.txt) allow otherwise. is it just me?

![image](https://github.com/awslabs/gluonts/assets/6527623/94c03fc8-eed1-4b73-aaaf-7fbfe5de93e2)

2023-10-20 08:20 UTC, shchur commented
Thanks @caseytomlin, we have released v0.13.7 that uses the old import style and therefore is compatible with the correct version ranges.

We will update the version ranges in v0.14.0, where the the new import style will be introduced.